// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5SWqIEgu1jat7GZUfKN2xhwRC76wgmKA',
    appId: '1:35685166777:web:eae0b055a78991ac65b568',
    messagingSenderId: '35685166777',
    projectId: 'parakeet-3241a',
    authDomain: 'parakeet-3241a.firebaseapp.com',
    storageBucket: 'parakeet-3241a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZjw6X5EBdX-vzehX_dPxVo-oGemI--c',
    appId: '1:35685166777:android:41843dc1d75fbe6d65b568',
    messagingSenderId: '35685166777',
    projectId: 'parakeet-3241a',
    storageBucket: 'parakeet-3241a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhylsIeAtocoSmXD1VUfbvrr_wmOPVxVY',
    appId: '1:35685166777:ios:6ca747eb75ce16a265b568',
    messagingSenderId: '35685166777',
    projectId: 'parakeet-3241a',
    storageBucket: 'parakeet-3241a.appspot.com',
    iosBundleId: 'com.sayankabir.parakeet',
  );
}
